function genEp(count) {
  return Array.from({ length: count }, (_, i) => `Episode ${i + 1}`);
}

export const SAGAS = [
  {
    id: "infinity",
    title: "The Infinity Saga",
    years: "2008–2019",
    color: "#4C8DFF",
    phaseNums: [1, 2, 3],
  },
  {
    id: "multiverse",
    title: "The Multiverse Saga",
    years: "2021–2027",
    color: "#8B7CF6",
    phaseNums: [4, 5, 6],
  },
];

export const PHASES = [
  {
    num: 1,
    color: "#4C8DFF",
    items: [
      { id: "p1-iron-man", type: "movie", title: "Iron Man", year: 2008 },
      {
        id: "p1-hulk",
        type: "movie",
        title: "The Incredible Hulk",
        year: 2008,
      },
      { id: "p1-iron-man-2", type: "movie", title: "Iron Man 2", year: 2010 },
      { id: "p1-thor", type: "movie", title: "Thor", year: 2011 },
      {
        id: "p1-cap1",
        type: "movie",
        title: "Captain America: The First Avenger",
        year: 2011,
      },
      { id: "p1-avengers", type: "movie", title: "The Avengers", year: 2012 },
      {
        id: "p1-os-consultant",
        type: "special",
        title: "The Consultant (One-Shot)",
        year: 2011,
      },
      {
        id: "p1-os-funny-thing",
        type: "special",
        title: "A Funny Thing Happened on the Way to Thor's Hammer (One-Shot)",
        year: 2011,
      },
    ],
  },
  {
    num: 2,
    color: "#4C8DFF",
    items: [
      { id: "p2-iron-man-3", type: "movie", title: "Iron Man 3", year: 2013 },
      {
        id: "p2-thor-2",
        type: "movie",
        title: "Thor: The Dark World",
        year: 2013,
      },
      {
        id: "p2-cap-2",
        type: "movie",
        title: "Captain America: The Winter Soldier",
        year: 2014,
      },
      {
        id: "p2-gotg",
        type: "movie",
        title: "Guardians of the Galaxy",
        year: 2014,
      },
      {
        id: "p2-aou",
        type: "movie",
        title: "Avengers: Age of Ultron",
        year: 2015,
      },
      { id: "p2-antman", type: "movie", title: "Ant-Man", year: 2015 },
      {
        id: "p2-os-item47",
        type: "special",
        title: "Item 47 (One-Shot)",
        year: 2012,
      },
      {
        id: "p2-os-agent-carter",
        type: "special",
        title: "Agent Carter (One-Shot)",
        year: 2013,
      },
      {
        id: "p2-os-all-hail",
        type: "special",
        title: "All Hail the King (One-Shot)",
        year: 2014,
      },
    ],
  },
  {
    num: 3,
    color: "#4C8DFF",
    items: [
      {
        id: "p3-civil-war",
        type: "movie",
        title: "Captain America: Civil War",
        year: 2016,
      },
      {
        id: "p3-doctor-strange",
        type: "movie",
        title: "Doctor Strange",
        year: 2016,
      },
      {
        id: "p3-gotg2",
        type: "movie",
        title: "Guardians of the Galaxy Vol. 2",
        year: 2017,
      },
      {
        id: "p3-homecoming",
        type: "movie",
        title: "Spider-Man: Homecoming",
        year: 2017,
      },
      { id: "p3-ragnarok", type: "movie", title: "Thor: Ragnarok", year: 2017 },
      {
        id: "p3-black-panther",
        type: "movie",
        title: "Black Panther",
        year: 2018,
      },
      {
        id: "p3-infinity-war",
        type: "movie",
        title: "Avengers: Infinity War",
        year: 2018,
      },
      {
        id: "p3-ant-wasp",
        type: "movie",
        title: "Ant-Man and the Wasp",
        year: 2018,
      },
      {
        id: "p3-captain-marvel",
        type: "movie",
        title: "Captain Marvel",
        year: 2019,
      },
      {
        id: "p3-endgame",
        type: "movie",
        title: "Avengers: Endgame",
        year: 2019,
      },
      {
        id: "p3-ffh",
        type: "movie",
        title: "Spider-Man: Far From Home",
        year: 2019,
      },
      { id: "p3-team-thor", type: "special", title: "Team Thor", year: 2016 },
      {
        id: "p3-team-thor-2",
        type: "special",
        title: "Team Thor: Part 2",
        year: 2017,
      },
      {
        id: "p3-team-darryl",
        type: "special",
        title: "Team Darryl",
        year: 2017,
      },
    ],
  },
  {
    num: 4,
    color: "#8B7CF6",
    items: [
      { id: "p4-black-widow", type: "movie", title: "Black Widow", year: 2021 },
      {
        id: "p4-wandavision",
        type: "tv",
        title: "WandaVision",
        year: 2021,
        episodes: [
          "Filmed Before a Live Studio Audience",
          "Don't Touch That Dial",
          "Now in Color",
          "We Interrupt This Program",
          "On a Very Special Episode...",
          "All-New Halloween Spooktacular!",
          "Breaking the Fourth Wall",
          "Previously On",
          "The Series Finale",
        ],
      },
      {
        id: "p4-falcon-ws",
        type: "tv",
        title: "The Falcon and the Winter Soldier",
        year: 2021,
        episodes: [
          "New World Order",
          "The Star-Spangled Man",
          "Power Broker",
          "The Whole World Is Watching",
          "Truth",
          "One World, One People",
        ],
      },
      {
        id: "p4-loki-s1",
        type: "tv",
        title: "Loki (Season 1)",
        year: 2021,
        episodes: [
          "Glorious Purpose",
          "The Variant",
          "Lamentis",
          "The Nexus Event",
          "Journey Into Mystery",
          "For All Time. Always.",
        ],
      },
      {
        id: "p4-whatif-s1",
        type: "tv",
        title: "What If...? (Season 1)",
        year: 2021,
        episodes: [
          "What If... Captain Carter Were Worthy?",
          "What If... T'Challa Became a Star-Lord?",
          "What If... The World Lost Its Mightiest Heroes?",
          "What If... Doctor Strange Lost His Heart Instead of His Hands?",
          "What If... Zombies?!",
          "What If... Killmonger Rescued Tony Stark?",
          "What If... Thor Were an Only Child?",
          "What If... Ultron Won?",
          "What If... The Watcher Broke His Oath?",
        ],
      },
      {
        id: "p4-shang-chi",
        type: "movie",
        title: "Shang-Chi and the Legend of the Ten Rings",
        year: 2021,
      },
      { id: "p4-eternals", type: "movie", title: "Eternals", year: 2021 },
      {
        id: "p4-hawkeye",
        type: "tv",
        title: "Hawkeye",
        year: 2021,
        episodes: [
          "Never Meet Your Heroes",
          "Hide and Seek",
          "Echoes",
          "Partners, Am I Right?",
          "Ronin",
          "So This Is Christmas?",
        ],
      },
      {
        id: "p4-nwh",
        type: "movie",
        title: "Spider-Man: No Way Home",
        year: 2021,
      },
      {
        id: "p4-moon-knight",
        type: "tv",
        title: "Moon Knight",
        year: 2022,
        episodes: [
          "The Goldfish Problem",
          "Summon the Suit",
          "The Friendly Type",
          "The Tomb",
          "Asylum",
          "Gods and Monsters",
        ],
      },
      {
        id: "p4-mom",
        type: "movie",
        title: "Doctor Strange in the Multiverse of Madness",
        year: 2022,
      },
      {
        id: "p4-ms-marvel",
        type: "tv",
        title: "Ms. Marvel",
        year: 2022,
        episodes: [
          "Generation Why",
          "Crushed",
          "Destined",
          "Seeing Red",
          "Time and Again",
          "No Normal",
        ],
      },
      {
        id: "p4-love-thunder",
        type: "movie",
        title: "Thor: Love and Thunder",
        year: 2022,
      },
      {
        id: "p4-she-hulk",
        type: "tv",
        title: "She-Hulk: Attorney at Law",
        year: 2022,
        episodes: [
          "A Normal Amount of Rage",
          "Superhuman Law",
          "The People vs. Emil Blonsky",
          "Is This Not Real Magic?",
          "Mean, Green, and Straight Poured into These Jeans",
          "Just Jen",
          "The Retreat",
          "Ribbit and Rip It",
          "Whose Show Is This?",
        ],
      },
      {
        id: "p4-i-am-groot-s1",
        type: "tv",
        title: "I Am Groot (Season 1)",
        year: 2022,
        episodes: genEp(5),
      },
      {
        id: "p4-werewolf",
        type: "special",
        title: "Werewolf by Night",
        year: 2022,
      },
      {
        id: "p4-wakanda-forever",
        type: "movie",
        title: "Black Panther: Wakanda Forever",
        year: 2022,
      },
      {
        id: "p4-gotg-holiday",
        type: "special",
        title: "The Guardians of the Galaxy Holiday Special",
        year: 2022,
      },
    ],
  },
  {
    num: 5,
    color: "#8B7CF6",
    items: [
      {
        id: "p5-quantumania",
        type: "movie",
        title: "Ant-Man and the Wasp: Quantumania",
        year: 2023,
      },
      {
        id: "p5-whatif-s2",
        type: "tv",
        title: "What If...? (Season 2)",
        year: 2023,
        episodes: genEp(9),
      },
      {
        id: "p5-i-am-groot-s2",
        type: "tv",
        title: "I Am Groot (Season 2)",
        year: 2023,
        episodes: genEp(6),
      },
      {
        id: "p5-secret-invasion",
        type: "tv",
        title: "Secret Invasion",
        year: 2023,
        episodes: [
          "Resurrection",
          "Promises",
          "Betrayed",
          "Beloved",
          "Harvest",
          "Home",
        ],
      },
      {
        id: "p5-gotg3",
        type: "movie",
        title: "Guardians of the Galaxy Vol. 3",
        year: 2023,
      },
      {
        id: "p5-loki-s2",
        type: "tv",
        title: "Loki (Season 2)",
        year: 2023,
        episodes: [
          "Ouroboros",
          "Breaking Brad",
          "1893",
          "Heart of the TVA",
          "Science/Fiction",
          "Glorious Purpose",
        ],
      },
      { id: "p5-the-marvels", type: "movie", title: "The Marvels", year: 2023 },
      {
        id: "p5-echo",
        type: "tv",
        title: "Echo",
        year: 2024,
        episodes: genEp(5),
      },
      {
        id: "p5-deadpool-wolverine",
        type: "movie",
        title: "Deadpool & Wolverine",
        year: 2024,
      },
      {
        id: "p5-agatha",
        type: "tv",
        title: "Agatha All Along",
        year: 2024,
        episodes: [
          "Seekest Thou the Road",
          "Circle Sewn With Fate, Unlock Thy Hidden Gate",
          "Through Many Miles, Of Tricks and Trials",
          "If I Can't Reach You Let My Song Teach You",
          "Darkest Hour, Wake Thy Power",
          "Familiar by Thy Side",
          "Death's Hand in Mine",
          "Follow Me My Friend, To Glory at the End",
          "Maiden Mother Crone",
        ],
      },
      {
        id: "p5-whatif-s3",
        type: "tv",
        title: "What If...? (Season 3)",
        year: 2024,
        episodes: genEp(10),
      },
      {
        id: "p5-yfns",
        type: "tv",
        title: "Your Friendly Neighborhood Spider-Man",
        year: 2025,
        episodes: genEp(10),
      },
      {
        id: "p5-daredevil-ba1",
        type: "tv",
        title: "Daredevil: Born Again (Season 1)",
        year: 2025,
        episodes: genEp(9),
      },
      {
        id: "p5-captain-america-bnw",
        type: "movie",
        title: "Captain America: Brave New World",
        year: 2025,
      },
      {
        id: "p5-ironheart",
        type: "tv",
        title: "Ironheart",
        year: 2025,
        episodes: genEp(6),
      },
      {
        id: "p5-thunderbolts",
        type: "movie",
        title: "Thunderbolts*",
        year: 2025,
      },
    ],
  },
  {
    num: 6,
    color: "#8B7CF6",
    items: [
      {
        id: "p6-fantastic-four",
        type: "movie",
        title: "The Fantastic Four: First Steps",
        year: 2025,
      },
      {
        id: "p6-eyes-of-wakanda",
        type: "tv",
        title: "Eyes of Wakanda",
        year: 2025,
        episodes: genEp(4),
      },
      {
        id: "p6-marvel-zombies",
        type: "tv",
        title: "Marvel Zombies",
        year: 2025,
        episodes: genEp(4),
      },
      {
        id: "p6-brand-new-day",
        type: "movie",
        title: "Spider-Man: Brand New Day",
        year: 2026,
        unreleased: true,
      },
      {
        id: "p6-doomsday",
        type: "movie",
        title: "Avengers: Doomsday",
        year: 2026,
        unreleased: true,
      },
      {
        id: "p6-wonder-man",
        type: "special",
        title: "Wonder Man",
        year: 2026,
        unreleased: true,
      },
      {
        id: "p6-daredevil-ba2",
        type: "special",
        title: "Daredevil: Born Again (Season 2)",
        year: 2027,
        unreleased: true,
      },
      {
        id: "p6-punisher",
        type: "special",
        title: "The Punisher: One Last Kill",
        year: 2027,
        unreleased: true,
      },
      {
        id: "p6-visionquest",
        type: "special",
        title: "VisionQuest",
        year: 2027,
        unreleased: true,
      },
      {
        id: "p6-secret-wars",
        type: "movie",
        title: "Avengers: Secret Wars",
        year: 2027,
        unreleased: true,
      },
    ],
  },
];

export const EXPANDED = [
  {
    id: "netflix",
    title: "Netflix Defenders Saga",
    color: "#B91C1C",
    blurb:
      "Street-level Marvel/ABC & Netflix series — now folded into the Sacred Timeline",
    items: [
      {
        id: "nf-dd-s1",
        type: "tv",
        title: "Daredevil (Season 1)",
        year: 2015,
        episodes: genEp(13),
      },
      {
        id: "nf-dd-s2",
        type: "tv",
        title: "Daredevil (Season 2)",
        year: 2016,
        episodes: genEp(13),
      },
      {
        id: "nf-jj-s1",
        type: "tv",
        title: "Jessica Jones (Season 1)",
        year: 2015,
        episodes: genEp(13),
      },
      {
        id: "nf-lc-s1",
        type: "tv",
        title: "Luke Cage (Season 1)",
        year: 2016,
        episodes: genEp(13),
      },
      {
        id: "nf-if-s1",
        type: "tv",
        title: "Iron Fist (Season 1)",
        year: 2017,
        episodes: genEp(13),
      },
      {
        id: "nf-defenders",
        type: "tv",
        title: "The Defenders",
        year: 2017,
        episodes: genEp(8),
      },
      {
        id: "nf-punisher-s1",
        type: "tv",
        title: "The Punisher (Season 1)",
        year: 2017,
        episodes: genEp(13),
      },
      {
        id: "nf-jj-s2",
        type: "tv",
        title: "Jessica Jones (Season 2)",
        year: 2018,
        episodes: genEp(13),
      },
      {
        id: "nf-lc-s2",
        type: "tv",
        title: "Luke Cage (Season 2)",
        year: 2018,
        episodes: genEp(13),
      },
      {
        id: "nf-if-s2",
        type: "tv",
        title: "Iron Fist (Season 2)",
        year: 2018,
        episodes: genEp(10),
      },
      {
        id: "nf-dd-s3",
        type: "tv",
        title: "Daredevil (Season 3)",
        year: 2018,
        episodes: genEp(13),
      },
      {
        id: "nf-punisher-s2",
        type: "tv",
        title: "The Punisher (Season 2)",
        year: 2019,
        episodes: genEp(13),
      },
      {
        id: "nf-jj-s3",
        type: "tv",
        title: "Jessica Jones (Season 3)",
        year: 2019,
        episodes: genEp(13),
      },
    ],
  },
  {
    id: "xmen",
    title: "Fox X-Men Universe",
    color: "#2563EB",
    blurb:
      "20th Century Fox's mutant saga, 2000–2020, now part of Disney's library",
    items: [
      { id: "xm-1", type: "movie", title: "X-Men", year: 2000 },
      { id: "xm-2", type: "movie", title: "X2: X-Men United", year: 2003 },
      { id: "xm-3", type: "movie", title: "X-Men: The Last Stand", year: 2006 },
      {
        id: "xm-origins-wolverine",
        type: "movie",
        title: "X-Men Origins: Wolverine",
        year: 2009,
      },
      {
        id: "xm-first-class",
        type: "movie",
        title: "X-Men: First Class",
        year: 2011,
      },
      { id: "xm-wolverine", type: "movie", title: "The Wolverine", year: 2013 },
      {
        id: "xm-dofp",
        type: "movie",
        title: "X-Men: Days of Future Past",
        year: 2014,
      },
      { id: "xm-deadpool", type: "movie", title: "Deadpool", year: 2016 },
      {
        id: "xm-apocalypse",
        type: "movie",
        title: "X-Men: Apocalypse",
        year: 2016,
      },
      { id: "xm-logan", type: "movie", title: "Logan", year: 2017 },
      { id: "xm-deadpool2", type: "movie", title: "Deadpool 2", year: 2018 },
      {
        id: "xm-dark-phoenix",
        type: "movie",
        title: "Dark Phoenix",
        year: 2019,
      },
      {
        id: "xm-new-mutants",
        type: "movie",
        title: "The New Mutants",
        year: 2020,
      },
    ],
  },
  {
    id: "spiderman",
    title: "Sony's Spider-Man Universe",
    color: "#DC2626",
    blurb:
      "Sony's own web-slinger continuities — live-action & the animated Spider-Verse",
    items: [
      { id: "sm-raimi-1", type: "movie", title: "Spider-Man", year: 2002 },
      { id: "sm-raimi-2", type: "movie", title: "Spider-Man 2", year: 2004 },
      { id: "sm-raimi-3", type: "movie", title: "Spider-Man 3", year: 2007 },
      {
        id: "sm-amazing-1",
        type: "movie",
        title: "The Amazing Spider-Man",
        year: 2012,
      },
      {
        id: "sm-amazing-2",
        type: "movie",
        title: "The Amazing Spider-Man 2",
        year: 2014,
      },
      {
        id: "sm-into-spiderverse",
        type: "movie",
        title: "Spider-Man: Into the Spider-Verse",
        year: 2018,
      },
      { id: "sm-venom-1", type: "movie", title: "Venom", year: 2018 },
      {
        id: "sm-venom-2",
        type: "movie",
        title: "Venom: Let There Be Carnage",
        year: 2021,
      },
      { id: "sm-morbius", type: "movie", title: "Morbius", year: 2022 },
      {
        id: "sm-across-spiderverse",
        type: "movie",
        title: "Spider-Man: Across the Spider-Verse",
        year: 2023,
      },
      { id: "sm-madame-web", type: "movie", title: "Madame Web", year: 2024 },
      {
        id: "sm-kraven",
        type: "movie",
        title: "Kraven the Hunter",
        year: 2024,
      },
      {
        id: "sm-venom-3",
        type: "movie",
        title: "Venom: The Last Dance",
        year: 2024,
      },
      {
        id: "sm-beyond-spiderverse",
        type: "movie",
        title: "Spider-Man: Beyond the Spider-Verse",
        year: 2027,
        unreleased: true,
      },
    ],
  },
];
